src/transition/transition.ts

Proposed fix for #16. This should not introduce any breaking changes, it should just give you the additional option of specifying  which properties do appear in `.params` (with types).
[Example in typescript playground](https://www.typescriptlang.org/play/#src=interface%20Transition%20%7B%0D%0A%20%20%20%20params(pathname%3F%3A%20string)%3A%20%7B%20%5Bkey%3A%20string%5D%3A%20any%20%7D%3B%0D%0A%0D%0A%20%20%20%20%2F%2F%20Suggested%20addition%2Fchange%0D%0A%20%20%20%20params%3CT%20extends%20%7B%20%5Bkey%3A%20string%5D%3A%20any%20%7D%3E(pathname%3F%3A%20string)%3A%20T%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20EXAMPLES%0D%0Ainterface%20MyStateParams%20%7B%0D%0A%20%20%20%20id%3A%20number%3B%0D%0A%20%20%20%20sort%3A%20string%3B%0D%0A%7D%0D%0A%20%20%20%20%0D%0A%2F%2F%20Currently%0D%0A(function%20(t)%20%7B%0D …

added option to use generic for Transition.params

---

src/vanilla/pushStateLocation.ts

call all event listeners in url() after pushing/replacing the history state to correctly sync the router
closes #23

fix(pushStateLocation): call listeners in url()

---

src/state/stateObject.ts

This PR targets [#3356](https://github.com/angular-ui/ui-router/issues/3356) opened up by me.
@christopherthielen 
I did not include an example. I thought it needs even more explanation. Hope the single sentence is clear enough.
Sorry, if I missed something. This is my first PR.

docs(State): align description of `state.State.includes` with actual implementation

---

src/url/urlMatcher.ts
test/urlMatcherFactorySpec.ts

urls with \r or \n symbols in them (%0D or %0A when encoded) are matched with catch-all syntax
close angular-ui/ui-router#3432

feat(urlMatcher): add support for multiline urls

---

src/url/interface.ts

Hello,
This is a docs fix to make the `otherwise` and `initial` examples match the API.
The current examples show the handler functions accepting 2 arguments, but they're actually passed 3 arguments, and in a different order. See [plnkr](http://plnkr.co/edit/wQhzenbxnGrL0bll6Ptx?p=preview).
The [type information says](https://github.com/ui-router/core/blob/5.0.5/src/url/urlRouter.ts#L275) the handlers should be of type [UrlRuleHandlerFn](https://github.com/ui-router/core/blob/5.0.5/src/url/interface.ts#L461), which has 3 arguments. This led me to believe that the examples were wrong, rather than there being a bug in the implementation.
I believe the issue was introduced in [eb2f5d7](https://github.com/ui-router/core/commit/eb2f5d7#diff-d9320a28c4e21a9a0cc99c6bb2939878R322) and then copied …

docs(UrlRulesApi): Fix examples for `otherwise` and `initial`

---

src/state/targetState.ts

It is recommended to use the primitive `string` whenever possible.
This also fixes the issue of passing the return value of `targetState.name()` to a method that accepts a `string`, which currently requires one to cast from `String` to `string`.

chore(typescript): Use primitive string type

---

src/url/urlRouter.ts

After a lot of research about what to use as a stable sorting algorithm, I found this to be the easiest, and it still uses `Array#sort` for good performance. I created the `stableSort` function in the same class, but if preferred I can move it.
Closes #66

Use stable sorting when sorting routes

---

src/path/pathFactory.ts

This is a patch to address an issue in sticky-states (https://github.com/ui-router/sticky-states/issues/13) where dynamic parameters were not working.
Updating PathUtils.treeChanges to return the retained nodes with the to parameters applied fixes the issue.

Update PathUtils.treeChanges to retained nodes with to params applied

---

src/resolve/resolvable.ts

I ran into this error when creating an AngularJS/Angular hybrid app. After digging into the problem, I found that the function 'isNullOrUndefined' was actually defined in 'common/predicates' not 'common'

import 'isNullOrUndefined' from correct place

---

src/common/trace.ts

Fixed the docs due to the fact that as of 1.0.0 'The npm package is renamed from angular-ui-router to @uirouter/angularjs'. https://github.com/angular-ui/ui-router/blob/master/CHANGELOG.md#notice-the-npm-package-is-renamed-from-angular-ui-router-to-uirouterangularjs

Renamed angular-ui-router import to @uirouter/angularjs

---

src/common/strings.ts

A typical edge (did they name the browser according to this 🤔) case in IE & Edge land - a difference in how `undefined` value is handled in `JSON.stringify` with replacer specified. For example, here's behavior in Chrome:
However, IE11 has quite a different mindset:
Notice that `console.log` wasn't called in IE version of the script - that caused a bug in the `stringify` function as well - `JSON.stringify` would return `undefined`, on which we'd then call `.replace` and obviously fail.
**Code to reproduce**
```js
JSON.stringify(undefined, console.log); // console.log should log output in browsers which follow spec.
```

Bugfix - stringify workaround for IE/Edge & undefined

---

src/state/stateBuilder.ts
test/lazyLoadSpec.ts

Fixed repeated {remainder:any} params error when future state is registered repeatedly. This scenario is typically happened during unit test.
Related: https://github.com/ui-router/core/commit/3cd5a2a#r31260154

fix(lazyLoad): StateBuilder should not mutate the state declaration

---

src/state/stateService.ts

fix(typescript): Mark `params` as optional in StateService.href

---

src/transition/interface.ts

With TypeScript's `strictNullChecks` set to `true`, I receive the following errors:
```
Property 'inactivating' of type 'PathNode[] | undefined' is not assignable to string index type 'PathNode[]'.ts(2411)
Property 'reactivating' of type 'PathNode[] | undefined' is not assignable to string index type 'PathNode[]'.ts(2411)
```
The following change fixes the error.

Fix error when `strictNullChecks: true`

---

src/resolve/interface.ts
src/resolve/resolvable.ts
test/resolveSpec.ts

Fixes https://github.com/ui-router/angular/issues/108

remove rxwait async policy in favour of allowing user defined async policy function

---

src/common/hof.ts
test/hofSpec.ts

fix(hof): Rewrite curry from scratch

---

src/state/targetState.ts
test/targetStateSpec.ts

Existing condition resulted in true even when an instance of `TargetState` was passed. This caused custom rules, returning an instance of `TargetState` from a `UrlRuleHandlerFn`, to perform a transition leading nowhere

fix(TargetState): make isDef check more thorough

---

src/url/interface.ts
src/url/urlConfig.ts
src/url/urlMatcher.ts
src/url/urlMatcherFactory.ts
test/urlMatcherFactorySpec.ts

fixes https://github.com/ui-router/angular/issues/340

fix not decoding encoded path and search params when synchronising the state with the current url.

---

src/url/urlMatcher.ts
test/urlMatcherFactorySpec.ts

Closes https://github.com/ui-router/angular/issues/867

fix(array): Fix decoding of array-type query parameters

---

src/common/strings.ts

`Rejection` is using stringify and therefore `Rejection.isRejectionPromise` has to be created dynamically in runtime and not as a global const

fix circular dependency with rejectFactory

---

.mergify.yml
package.json
src/params/stateParams.ts
test/stateServiceSpec.ts
yarn.lock

Make sure `$state.href` (and by extension `uiSref`) handle `inherit: false`
